//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplexModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.HomeAddress = new Address();
            this.BusinessAddress = new Address();
        }
    
        public int CustomerId { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
    
        public Address HomeAddress { get; set; }
        public Address BusinessAddress { get; set; }
    }
}
