//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplexModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeComponent
    {
        public int RecipeID { get; set; }
        public int IngredientID { get; set; }
        public Nullable<int> MadeFromRecipe { get; set; }
        public Nullable<int> AmountOfRecipe { get; set; }
    
        public virtual Recipe Recipe { get; set; }
    }
}
