//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplexModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SplitCustomer
    {
        public int CustomerID { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string HomeAddressStreet { get; set; }
        public string HomeAddressState { get; set; }
        public string HomeAddressZip { get; set; }
        public string HomeAddressCity { get; set; }
        public string BusinessAddressStreet { get; set; }
        public string BusinessAddressState { get; set; }
        public string BusinessAddressZip { get; set; }
        public string BusinessAddressCity { get; set; }
    }
}
