//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplexModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPTBakedGood : TPTIngredient
    {
        public Nullable<decimal> BakersPercentage { get; set; }
        public Nullable<decimal> FatPercentage { get; set; }
        public Nullable<decimal> LiquidPercentage { get; set; }
    }
}
